version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build library
          command: yarn run release
      - run:
          name: Run unit tests
          command: yarn run test:coverage
      - run:
          name: Run e2e tests
          command: yarn run test:e2e
      - run:
         name: Submit to Codecov
         command: yarn run codecov
